# Тема: Часові ряди та напівструктуровані дані у задачах ML
## Домашнє завдання № 5 (Тема 7)

## 1. Setup і завантаження даних

In [1]:
# Install PostgreSQL
!apt-get -qq update > /dev/null
!apt-get -qq install -y postgresql > /dev/null
# Start PostgreSQL
!service postgresql start
# Set password for the postgres user
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
# Install SQLAlchemy, PostgreSQL driver and other libraries
!pip install -q sqlalchemy psycopg2-binary pandas pyarrow requests

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]
ALTER ROLE

Import libraries

In [2]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.request import urlretrieve

In [3]:
# Create database engine
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
)
# Test connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.scalar())

PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

Завантаження NYC Taxi з офіційного Parquet

In [4]:
URL = (
    'https://d37ci6vzurychx.cloudfront.net/trip-data/'
    'yellow_tripdata_2026-08.parquet'
)

parquet_path = '/content/yellow_tripdata_2026-08.parquet'
urlretrieve(URL, parquet_path)

columns = [
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime',
    'PULocationID',
    'DOLocationID',
    'trip_distance',
    'fare_amount',
    'passenger_count',
]

df = pd.read_parquet(parquet_path, columns=columns).head(500_000)

# Basic cleaning before loading to PostgreSQL
df = df[(df['fare_amount'] > 0) & (df['fare_amount'] < 500)]
df = df[(df['trip_distance'] > 0) & (df['trip_distance'] < 100)]
df = df[df['PULocationID'].notna()]

df.to_sql(
    'nyc_taxi_raw',
    engine,
    if_exists='replace',
    index=False,
    chunksize=10_000,
)

pd.read_sql('SELECT COUNT(*) AS n_rows FROM nyc_taxi_raw', engine)

   n_rows
0  490173

Створення daily aggregation таблиці (t7_hw_taxi_daily) для реальних TLC-даних (Taxi and Limousine Commission)

In [6]:
sql = """
DROP TABLE IF EXISTS t7_hw_taxi_daily;

CREATE TABLE t7_hw_taxi_daily AS
SELECT
    "PULocationID"::INTEGER AS pickup_zone_id,
    DATE_TRUNC('day', tpep_pickup_datetime::TIMESTAMP)::DATE AS ts_day,
    COUNT(*)::INTEGER AS trip_count,
    AVG(fare_amount)::NUMERIC(10, 2) AS avg_fare,
    SUM(trip_distance)::NUMERIC(12, 2) AS total_distance
FROM nyc_taxi_raw
WHERE fare_amount > 0
  AND fare_amount < 500
  AND trip_distance > 0
  AND trip_distance < 100
  AND "PULocationID" IS NOT NULL
GROUP BY
    "PULocationID"::INTEGER,
    DATE_TRUNC('day', tpep_pickup_datetime::TIMESTAMP)::DATE;

ALTER TABLE t7_hw_taxi_daily
    ADD PRIMARY KEY (pickup_zone_id, ts_day);
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Daily aggregation table created successfully!")

Daily aggregation table created successfully!

In [7]:
sql = """
SELECT pickup_zone_id, COUNT(*) AS n_days
FROM t7_hw_taxi_daily
GROUP BY pickup_zone_id
ORDER BY pickup_zone_id
LIMIT 10;
"""

pd.read_sql(sql, engine)

   pickup_zone_id  n_days
0               1       6
1               2       1
2               3       3
3               4       6
4               6       5
5               7       6
6               8       2
7               9       2
8              10       6
9              11       2

Створення окремої демонстраційної typed-таблиці з TIMESTAMPTZ

In [8]:
sql = """
DROP TABLE IF EXISTS t7_hw_taxi_trips_typed;

CREATE TABLE t7_hw_taxi_trips_typed AS
SELECT
    "PULocationID"::INTEGER AS pickup_zone_id,
    "DOLocationID"::INTEGER AS dropoff_zone_id,
    (tpep_pickup_datetime::TIMESTAMP AT TIME ZONE 'America/New_York') AS pickup_at,
    (tpep_dropoff_datetime::TIMESTAMP AT TIME ZONE 'America/New_York') AS dropoff_at,
    trip_distance::NUMERIC(10, 2) AS trip_distance,
    fare_amount::NUMERIC(10, 2) AS fare_amount,
    passenger_count::INTEGER AS passenger_count
FROM nyc_taxi_raw
WHERE fare_amount > 0
  AND fare_amount < 500
  AND trip_distance > 0
  AND trip_distance < 100;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Typed table created successfully!")

Typed table created successfully!

In [21]:
sql = """
SELECT pickup_at, pg_typeof(pickup_at) AS pickup_type
FROM t7_hw_taxi_trips_typed
LIMIT 5;
"""

pd.read_sql(sql, engine)

                  pickup_at               pickup_type
0 2026-08-01 04:03:04+00:00  timestamp with time zone
1 2026-08-01 04:38:45+00:00  timestamp with time zone
2 2026-08-01 04:54:51+00:00  timestamp with time zone
3 2026-08-01 04:27:35+00:00  timestamp with time zone
4 2026-08-01 04:39:08+00:00  timestamp with time zone

## 2. Time-series ML features

### Feature 1. Lag features: lag-1d, lag-7d, lag-30d

In [23]:
sql = """
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    LAG(trip_count, 1)  OVER w AS trips_lag_1d,
    LAG(trip_count, 7)  OVER w AS trips_lag_7d,
    LAG(trip_count, 30) OVER w AS trips_lag_30d
FROM t7_hw_taxi_daily
WINDOW w AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20;
"""

pd.read_sql(sql, engine)

,pickup_zone_id,ts_day,trip_count,trips_lag_1d,trips_lag_7d,trips_lag_30d
0,1,2026-08-01,4,NaN,None,None
1,1,2026-08-02,5,4.0,None,None
2,1,2026-08-03,1,5.0,None,None
3,1,2026-08-04,3,1.0,None,None
4,1,2026-08-05,1,3.0,None,None
5,1,2026-08-06,6,1.0,None,None
6,2,2026-08-05,1,NaN,None,None
7,3,2026-08-01,2,NaN,None,None
8,3,2026-08-02,2,2.0,None,None
9,3,2026-08-03,2,2.0,None,None
10,4,2026-08-01,277,NaN,None,None
11,4,2026-08-02,211,277.0,None,None
12,4,2026-08-03,55,211.0,None,None
13,4,2026-08-04,119,55.0,None,None
14,4,2026-08-05,98,119.0,None,None
15,4,2026-08-06,86,98.0,None,None
16,6,2026-08-01,1,NaN,None,None
17,6,2026-08-03,4,1.0,None,None
18,6,2026-08-04,3,4.0,None,None
19,6,2026-08-05,2,3.0,None,None

### Feature 2. Rolling 7-day average fare

In [24]:
sql = """
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    AVG(avg_fare) OVER w7 AS rolling_avg_fare_7d,
    COUNT(*)      OVER w7 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w7 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20;
"""

pd.read_sql(sql, engine)

    pickup_zone_id      ts_day  avg_fare  rolling_avg_fare_7d  days_in_window
0                1  2026-08-01    116.75           116.750000               1
1                1  2026-08-02     75.49            96.120000               2
2                1  2026-08-03    120.00           104.080000               3
3                1  2026-08-04    126.67           109.727500               4
4                1  2026-08-05     30.00            93.782000               5
5                1  2026-08-06    107.67            96.096667               6
6                2  2026-08-05     16.30            16.300000               1
7                3  2026-08-01     32.03            32.030000               1
8                3  2026-08-02     30.55            31.290000               2
9                3  2026-08-03      4.69            22.423333               3
10               4  2026-08-01     15.99            15.990000               1
11               4  2026-08-02     16.85            16.420000               2
12               4  2026-08-03     17.35            16.730000               3
13               4  2026-08-04     17.31            16.875000               4
14               4  2026-08-05     17.29            16.958000               5
15               4  2026-08-06     18.01            17.133333               6
16               6  2026-08-01      0.01             0.010000               1
17               6  2026-08-03      2.16             1.085000               2
18               6  2026-08-04      0.01             0.726667               3
19               6  2026-08-05      0.01             0.547500               4

### Feature 3. Rolling 30-day fare volatility

In [26]:
sql = """
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,
    COUNT(*)              OVER w30 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w30 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20;
"""

pd.read_sql(sql, engine)

    pickup_zone_id      ts_day  avg_fare  rolling_std_fare_30d  days_in_window
0                1  2026-08-01    116.75                   NaN               1
1                1  2026-08-02     75.49             29.175226               2
2                1  2026-08-03    120.00             24.812934               3
3                1  2026-08-04    126.67             23.195506               4
4                1  2026-08-05     30.00             40.924546               5
5                1  2026-08-06    107.67             37.040530               6
6                2  2026-08-05     16.30                   NaN               1
7                3  2026-08-01     32.03                   NaN               1
8                3  2026-08-02     30.55              1.046518               2
9                3  2026-08-03      4.69             15.375335               3
10               4  2026-08-01     15.99                   NaN               1
11               4  2026-08-02     16.85              0.608112               2
12               4  2026-08-03     17.35              0.687895               3
13               4  2026-08-04     17.31              0.632113               4
14               4  2026-08-05     17.29              0.578031               5
15               4  2026-08-06     18.01              0.672121               6
16               6  2026-08-01      0.01                   NaN               1
17               6  2026-08-03      2.16              1.520280               2
18               6  2026-08-04      0.01              1.241303               3
19               6  2026-08-05      0.01              1.075000               4

### Feature 4. Expanding cumulative trips

In [28]:
sql = """
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    SUM(trip_count) OVER we AS cumulative_trips,
    AVG(trip_count) OVER we AS expanding_avg_trips
FROM t7_hw_taxi_daily
WINDOW we AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20;
"""

pd.read_sql(sql, engine)

,pickup_zone_id,ts_day,trip_count,cumulative_trips,expanding_avg_trips
0,1,2026-08-01,4,4,4.000000
1,1,2026-08-02,5,9,4.500000
2,1,2026-08-03,1,10,3.333333
3,1,2026-08-04,3,13,3.250000
4,1,2026-08-05,1,14,2.800000
5,1,2026-08-06,6,20,3.333333
6,2,2026-08-05,1,1,1.000000
7,3,2026-08-01,2,2,2.000000
8,3,2026-08-02,2,4,2.000000
9,3,2026-08-03,2,6,2.000000
10,4,2026-08-01,277,277,277.000000
11,4,2026-08-02,211,488,244.000000
12,4,2026-08-03,55,543,181.000000
13,4,2026-08-04,119,662,165.500000
14,4,2026-08-05,98,760,152.000000
15,4,2026-08-06,86,846,141.000000
16,6,2026-08-01,1,1,1.000000
17,6,2026-08-03,4,5,2.500000
18,6,2026-08-04,3,8,2.666667
19,6,2026-08-05,2,10,2.500000

### Combined feature view

In [44]:
sql = """
DROP VIEW IF EXISTS v_t7_hw_taxi_features;

CREATE VIEW v_t7_hw_taxi_features AS
WITH features_basic AS (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        avg_fare,
        total_distance,

        LAG(trip_count, 1)  OVER w_pid AS trips_lag_1d,
        LAG(trip_count, 7)  OVER w_pid AS trips_lag_7d,
        LAG(trip_count, 30) OVER w_pid AS trips_lag_30d,

        AVG(avg_fare) OVER w7 AS rolling_avg_fare_7d,
        STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,

        SUM(trip_count) OVER we AS cumulative_trips,
        AVG(trip_count) OVER we AS expanding_avg_trips
    FROM t7_hw_taxi_daily
    WINDOW
        w_pid AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
        ),
        w7 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
        ),
        w30 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
        ),
        we AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )
)
SELECT *
FROM features_basic
WHERE trips_lag_1d IS NOT NULL;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Combined feature view table created successfully!")

Combined feature view table created successfully!

In [49]:
sql = """
SELECT *
FROM v_t7_hw_taxi_features
ORDER BY pickup_zone_id, ts_day
LIMIT 20;
"""

pd.read_sql(sql, engine)

,pickup_zone_id,ts_day,trip_count,avg_fare,total_distance,trips_lag_1d,trips_lag_7d,trips_lag_30d,rolling_avg_fare_7d,rolling_std_fare_30d,cumulative_trips,expanding_avg_trips
0,1,2026-08-02,5,75.49,3.34,4,None,None,96.120000,29.175226,9,4.500000
1,1,2026-08-03,1,120.00,0.01,5,None,None,104.080000,24.812934,10,3.333333
2,1,2026-08-04,3,126.67,0.29,1,None,None,109.727500,23.195506,13,3.250000
3,1,2026-08-05,1,30.00,0.01,3,None,None,93.782000,40.924546,14,2.800000
4,1,2026-08-06,6,107.67,0.95,1,None,None,96.096667,37.040530,20,3.333333
5,3,2026-08-02,2,30.55,17.00,2,None,None,31.290000,1.046518,4,2.000000
6,3,2026-08-03,2,4.69,1.80,2,None,None,22.423333,15.375335,6,2.000000
7,4,2026-08-02,211,16.85,605.59,277,None,None,16.420000,0.608112,488,244.000000
8,4,2026-08-03,55,17.35,159.65,211,None,None,16.730000,0.687895,543,181.000000
9,4,2026-08-04,119,17.31,304.28,55,None,None,16.875000,0.632113,662,165.500000
10,4,2026-08-05,98,17.29,278.39,119,None,None,16.958000,0.578031,760,152.000000
11,4,2026-08-06,86,18.01,224.26,98,None,None,17.133333,0.672121,846,141.000000
12,6,2026-08-03,4,2.16,19.67,1,None,None,1.085000,1.520280,5,2.500000
13,6,2026-08-04,3,0.01,20.29,4,None,None,0.726667,1.241303,8,2.666667
14,6,2026-08-05,2,0.01,16.98,3,None,None,0.547500,1.075000,10,2.500000
15,6,2026-08-06,2,0.01,12.78,2,None,None,0.440000,0.961509,12,2.400000
16,7,2026-08-02,56,22.60,249.31,75,None,None,21.610000,1.400071,131,65.500000
17,7,2026-08-03,52,23.96,192.38,56,None,None,22.393333,1.679563,183,61.000000
18,7,2026-08-04,49,22.25,154.15,52,None,None,22.357500,1.373229,232,58.000000
19,7,2026-08-05,36,25.76,128.39,49,None,None,23.038000,1.931248,268,53.600000

## 3. JSONB-таблиця для подій

Створення синтетичної таблиці t7_hw_events для ML event-log.

In [51]:
sql = """
DROP TABLE IF EXISTS t7_hw_events;

CREATE TABLE t7_hw_events (
    event_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    event_ts    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type  TEXT NOT NULL,
    payload     JSONB NOT NULL
);

INSERT INTO t7_hw_events (user_id, event_ts, event_type, payload)
SELECT
    (n % 1000) + 1 AS user_id,
    TIMESTAMPTZ '2024-04-01 00:00:00+00'
        - ((n % 60) || ' days')::INTERVAL AS event_ts,
    CASE (n % 5)
        WHEN 0 THEN 'page_view'
        WHEN 1 THEN 'click'
        WHEN 2 THEN 'add_to_cart'
        WHEN 3 THEN 'checkout'
        ELSE        'recommendation_shown'
    END AS event_type,
    CASE (n % 5)
        WHEN 0 THEN jsonb_build_object(
            'url', '/product/' || ((n % 200) + 1),
            'referrer', (ARRAY['google','direct','email','fb'])[(n % 4) + 1],
            'device', (ARRAY['mobile','desktop','tablet'])[(n % 3) + 1]
        )
        WHEN 1 THEN jsonb_build_object(
            'element_id', 'btn_' || ((n % 50) + 1),
            'page_url', '/category/' || ((n % 20) + 1),
            'device', (ARRAY['mobile','desktop'])[(n % 2) + 1]
        )
        WHEN 2 THEN jsonb_build_object(
            'product_id', (n % 200) + 1,
            'price', ((n % 100) + 10)::NUMERIC(10, 2),
            'quantity', (n % 5) + 1,
            'tags', jsonb_build_array(
                (ARRAY['promo','new','clearance'])[(n % 3) + 1]
            )
        )
        WHEN 3 THEN jsonb_build_object(
            'order_id', 'o_' || (n + 100000),
            'total', ((n % 500) + 50)::NUMERIC(10, 2),
            'items_count', (n % 10) + 1,
            'payment_method', (ARRAY['card','paypal','crypto'])[(n % 3) + 1]
        )
        ELSE jsonb_build_object(
            'model_name', 'rec_v' || ((n % 5) + 1),
            'model_version', '1.' || (n % 10),
            'recommendations', jsonb_build_array(
                (n % 200) + 1,
                ((n + 1) % 200) + 1,
                ((n + 2) % 200) + 1
            ),
            'experiment', 'exp_' || ((n % 3) + 1)
        )
    END AS payload
FROM generate_series(1, 50000) AS n;

ANALYZE t7_hw_events;

SELECT event_type, COUNT(*) AS n_events
FROM t7_hw_events
GROUP BY event_type
ORDER BY event_type;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Synthetic table created successfully!")

Synthetic table created successfully!

Перевірка створених синтетичних даних

In [52]:
sql = """
SELECT * FROM t7_hw_events LIMIT 10
"""

pd.read_sql(sql, engine)

,event_id,user_id,event_ts,event_type,payload
0,1,2,2024-03-31 00:00:00+00:00,click,"{'device': 'desktop', 'page_url': '/category/2..."
1,2,3,2024-03-30 00:00:00+00:00,add_to_cart,"{'tags': ['clearance'], 'price': 12.0, 'quanti..."
2,3,4,2024-03-29 00:00:00+00:00,checkout,"{'total': 53.0, 'order_id': 'o_100003', 'items..."
3,4,5,2024-03-28 00:00:00+00:00,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
4,5,6,2024-03-27 00:00:00+00:00,page_view,"{'url': '/product/6', 'device': 'tablet', 'ref..."
5,6,7,2024-03-26 00:00:00+00:00,click,"{'device': 'mobile', 'page_url': '/category/7'..."
6,7,8,2024-03-25 00:00:00+00:00,add_to_cart,"{'tags': ['new'], 'price': 17.0, 'quantity': 3..."
7,8,9,2024-03-24 00:00:00+00:00,checkout,"{'total': 58.0, 'order_id': 'o_100008', 'items..."
8,9,10,2024-03-23 00:00:00+00:00,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
9,10,11,2024-03-22 00:00:00+00:00,page_view,"{'url': '/product/11', 'device': 'desktop', 'r..."

### JSONB Query 1. Containment `@>`

Знаходимо 10 оформлень замовлення оплачених карткою.

In [53]:
sql = """
SELECT event_id, user_id, event_ts, payload
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND payload @> jsonb_build_object('payment_method', 'card')
LIMIT 10;
"""

pd.read_sql(sql, engine)

,event_id,user_id,event_ts,payload
0,3,4,2024-03-29 00:00:00+00:00,"{'total': 53.0, 'order_id': 'o_100003', 'items..."
1,18,19,2024-03-14 00:00:00+00:00,"{'total': 68.0, 'order_id': 'o_100018', 'items..."
2,33,34,2024-02-28 00:00:00+00:00,"{'total': 83.0, 'order_id': 'o_100033', 'items..."
3,48,49,2024-02-13 00:00:00+00:00,"{'total': 98.0, 'order_id': 'o_100048', 'items..."
4,63,64,2024-03-29 00:00:00+00:00,"{'total': 113.0, 'order_id': 'o_100063', 'item..."
5,78,79,2024-03-14 00:00:00+00:00,"{'total': 128.0, 'order_id': 'o_100078', 'item..."
6,93,94,2024-02-28 00:00:00+00:00,"{'total': 143.0, 'order_id': 'o_100093', 'item..."
7,108,109,2024-02-13 00:00:00+00:00,"{'total': 158.0, 'order_id': 'o_100108', 'item..."
8,123,124,2024-03-29 00:00:00+00:00,"{'total': 173.0, 'order_id': 'o_100123', 'item..."
9,138,139,2024-03-14 00:00:00+00:00,"{'total': 188.0, 'order_id': 'o_100138', 'item..."

### JSONB Query 2. Key existence `?` та `?|`

Запит повертає 10 подій, у яких JSONB-поле payload містить ключ tags.

In [54]:
sql = """
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ? 'tags'
LIMIT 10;
"""

pd.read_sql(sql, engine)

   event_id   event_type                                            payload
0         2  add_to_cart  {'tags': ['clearance'], 'price': 12.0, 'quanti...
1         7  add_to_cart  {'tags': ['new'], 'price': 17.0, 'quantity': 3...
2        12  add_to_cart  {'tags': ['promo'], 'price': 22.0, 'quantity':...
3        17  add_to_cart  {'tags': ['clearance'], 'price': 27.0, 'quanti...
4        22  add_to_cart  {'tags': ['new'], 'price': 32.0, 'quantity': 3...
5        27  add_to_cart  {'tags': ['promo'], 'price': 37.0, 'quantity':...
6        32  add_to_cart  {'tags': ['clearance'], 'price': 42.0, 'quanti...
7        37  add_to_cart  {'tags': ['new'], 'price': 47.0, 'quantity': 3...
8        42  add_to_cart  {'tags': ['promo'], 'price': 52.0, 'quantity':...
9        47  add_to_cart  {'tags': ['clearance'], 'price': 57.0, 'quanti...

Запит повертає 10 подій, у яких payload містить хоча б один із ключів experiment або model_version.

In [55]:
sql = """
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ?| ARRAY['experiment', 'model_version']
LIMIT 10;
"""

pd.read_sql(sql, engine)

,event_id,event_type,payload
0,4,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
1,9,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
2,14,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
3,19,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
4,24,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
5,29,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
6,34,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
7,39,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
8,44,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
9,49,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."

### JSONB Query 3. JSONPath

Запит виводить 15 подій показу рекомендацій і витягує з payload кожен елемент масиву recommendations.

In [56]:
sql = """
SELECT
    event_id,
    jsonb_path_query(payload, '$.recommendations[*]') AS recommended_pid
FROM t7_hw_events
WHERE event_type = 'recommendation_shown'
LIMIT 15;
"""

pd.read_sql(sql, engine)

    event_id  recommended_pid
0          4                5
1          4                6
2          4                7
3          9               10
4          9               11
5          9               12
6         14               15
7         14               16
8         14               17
9         19               20
10        19               21
11        19               22
12        24               25
13        24               26
14        24               27

Запит знаходить 10 подій оформлення замовлення (checkout), у яких сума замовлення перевищує 300.

In [66]:
sql = """
SELECT
    event_id,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND jsonb_path_exists(payload, '$.total ? (@ > 300)')
LIMIT 10;
"""

pd.read_sql(sql, engine)

   event_id  order_id  total
0       253  o_100253  303.0
1       258  o_100258  308.0
2       263  o_100263  313.0
3       268  o_100268  318.0
4       273  o_100273  323.0
5       278  o_100278  328.0
6       283  o_100283  333.0
7       288  o_100288  338.0
8       293  o_100293  343.0
9       298  o_100298  348.0

## 4. GIN-index demo + EXPLAIN ANALYZE

### Step 1. Containment query без GIN-індексу

In [69]:
sql = """
DROP INDEX IF EXISTS idx_t7_events_payload_gin_pathops;
DROP INDEX IF EXISTS idx_t7_events_payload_gin_ops;
DROP INDEX IF EXISTS idx_t7_events_device_btree;

ANALYZE t7_hw_events;

EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
"""

pd.read_sql(sql, engine)

                                          QUERY PLAN
0  Aggregate  (cost=1757.39..1757.40 rows=1 width...
1                           Buffers: shared hit=1000
2    ->  Seq Scan on t7_hw_events  (cost=0.00..17...
3          Filter: (payload @> jsonb_build_object...
4                      Rows Removed by Filter: 46666
5                           Buffers: shared hit=1000
6                                          Planning:
7                              Buffers: shared hit=6
8                            Planning Time: 0.187 ms
9                          Execution Time: 70.927 ms

### Step 2. GIN-індекс для containment / JSONPath workload

In [87]:
sql = """
CREATE INDEX idx_t7_events_payload_gin_pathops
    ON t7_hw_events USING GIN (payload jsonb_path_ops);
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("GIN-index created successfully!")

GIN-index created successfully!

In [91]:
sql = """
ANALYZE t7_hw_events;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Analysis completed successfully!")

Analysis completed successfully!

In [92]:
sql = """
SELECT pg_size_pretty(pg_relation_size('idx_t7_events_payload_gin_pathops'))
       AS gin_index_size;
"""

pd.read_sql(sql, engine)

  gin_index_size
0        1144 kB

### Step 3. Той самий containment query після GIN

In [93]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
"""

pd.read_sql(sql, engine)

                                           QUERY PLAN
0   Aggregate  (cost=1106.52..1106.53 rows=1 width...
1                            Buffers: shared hit=1004
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: (payload @> jsonb_build_...
4                             Heap Blocks: exact=1000
5                            Buffers: shared hit=1004
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: (payload @> jsonb_bu...
8                               Buffers: shared hit=4
9                                           Planning:
10                             Buffers: shared hit=14
11                            Planning Time: 0.405 ms
12                           Execution Time: 9.589 ms

In [95]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('referrer', 'google');
"""

pd.read_sql(sql, engine)

                                           QUERY PLAN
0   Aggregate  (cost=1079.85..1079.86 rows=1 width...
1                            Buffers: shared hit=1004
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: (payload @> jsonb_build_...
4                             Heap Blocks: exact=1000
5                            Buffers: shared hit=1004
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: (payload @> jsonb_bu...
8                               Buffers: shared hit=4
9                                           Planning:
10                              Buffers: shared hit=1
11                            Planning Time: 0.216 ms
12                          Execution Time: 10.896 ms

Замість Seq Scan у першому запиті без GIN-індексу тут появляються Bitmap Heap Scan та Bitmap Index Scan. GIN індекс створений коректно. Замість майже 71 мс (для неіндексованого) час виконання падає для запитів до 9-11 мс після створення GIN індексу.

### Step 4. Коли GIN не допомагає: path-specific text equality

In [96]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile';
"""

pd.read_sql(sql, engine)

                                          QUERY PLAN
0  Aggregate  (cost=1750.62..1750.63 rows=1 width...
1                           Buffers: shared hit=1000
2    ->  Seq Scan on t7_hw_events  (cost=0.00..17...
3          Filter: ((payload ->> 'device'::text) ...
4                      Rows Removed by Filter: 41667
5                           Buffers: shared hit=1000
6                            Planning Time: 0.134 ms
7                          Execution Time: 35.032 ms

Cтворюємо expression index

In [97]:
sql = """
CREATE INDEX idx_t7_events_device_btree
    ON t7_hw_events ((payload ->> 'device'));
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Expression index created successfully!")

Expression index created successfully!

In [98]:
sql = """
ANALYZE t7_hw_events;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Analysis completed successfully!")

Analysis completed successfully!

In [99]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile';
"""

pd.read_sql(sql, engine)

                                           QUERY PLAN
0   Aggregate  (cost=1242.75..1242.76 rows=1 width...
1                     Buffers: shared hit=1000 read=9
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: ((payload ->> 'device'::...
4                             Heap Blocks: exact=1000
5                     Buffers: shared hit=1000 read=9
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: ((payload ->> 'devic...
8                              Buffers: shared read=9
9                                           Planning:
10                       Buffers: shared hit=5 read=1
11                            Planning Time: 0.320 ms
12                           Execution Time: 5.085 ms

Замість Seq Scan у першому запиті без Expression-індексу тут появляються Bitmap Heap Scan та Bitmap Index Scan. Expression індекс створений коректно. Замість майже 35 мс (для неіндексованого) час виконання падає для запиту до 5 мс після створення Expression індексу.

## 5. JSONB vs normalized + Reflection

### Step 1. Нормалізована таблиця для checkout-подій

In [100]:
sql = """
DROP TABLE IF EXISTS t7_hw_checkouts_norm;

CREATE TABLE t7_hw_checkouts_norm (
    event_id        INTEGER PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    event_ts        TIMESTAMPTZ NOT NULL,
    order_id        TEXT NOT NULL,
    total           NUMERIC(10, 2) NOT NULL,
    items_count     INTEGER NOT NULL CHECK (items_count > 0),
    payment_method  TEXT NOT NULL CHECK (payment_method IN ('card', 'paypal', 'crypto'))
);

INSERT INTO t7_hw_checkouts_norm (
    event_id,
    user_id,
    event_ts,
    order_id,
    total,
    items_count,
    payment_method
)
SELECT
    event_id,
    user_id,
    event_ts,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total,
    (payload ->> 'items_count')::INTEGER AS items_count,
    payload ->> 'payment_method' AS payment_method
FROM t7_hw_events
WHERE event_type = 'checkout';

CREATE INDEX idx_t7_checkouts_norm_pm
    ON t7_hw_checkouts_norm (payment_method);

ANALYZE t7_hw_checkouts_norm;
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("Normalized table created successfully!")

Normalized table created successfully!

In [101]:
sql = """
SELECT COUNT(*) AS n_checkouts
FROM t7_hw_checkouts_norm;
"""

pd.read_sql(sql, engine)

   n_checkouts
0        10000

### Step 2. Один запит двома способами

JSONB-версія:

In [102]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payload ->> 'payment_method' AS payment_method,
    AVG((payload ->> 'total')::NUMERIC) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_events
WHERE event_type = 'checkout'
GROUP BY payload ->> 'payment_method'
ORDER BY avg_total DESC
LIMIT 3;
"""

pd.read_sql(sql, engine)

                                           QUERY PLAN
0   Limit  (cost=1952.25..1952.26 rows=3 width=72)...
1                            Buffers: shared hit=1000
2     ->  Sort  (cost=1952.25..1966.00 rows=5501 w...
3           Sort Key: (avg(((payload ->> 'total'::...
4                Sort Method: quicksort  Memory: 25kB
5                            Buffers: shared hit=1000
6           ->  HashAggregate  (cost=1798.64..1881...
7                 Group Key: (payload ->> 'payment...
8                     Batches: 1  Memory Usage: 217kB
9                            Buffers: shared hit=1000
10                ->  Seq Scan on t7_hw_events  (c...
11                      Filter: (event_type = 'che...
12                      Rows Removed by Filter: 40000
13                           Buffers: shared hit=1000
14                                          Planning:
15                      Buffers: shared hit=15 read=1
16                            Planning Time: 0.813 ms
17                          Execution Time: 17.481 ms

Normalized-версія:

In [103]:
sql = """
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payment_method,
    AVG(total) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_checkouts_norm
GROUP BY payment_method
ORDER BY avg_total DESC
LIMIT 3;
"""

pd.read_sql(sql, engine)

                                           QUERY PLAN
0   Limit  (cost=269.06..269.07 rows=3 width=46) (...
1                              Buffers: shared hit=94
2     ->  Sort  (cost=269.06..269.07 rows=3 width=...
3                         Sort Key: (avg(total)) DESC
4                Sort Method: quicksort  Memory: 25kB
5                              Buffers: shared hit=94
6           ->  HashAggregate  (cost=269.00..269.0...
7                           Group Key: payment_method
8                      Batches: 1  Memory Usage: 24kB
9                              Buffers: shared hit=94
10                ->  Seq Scan on t7_hw_checkouts_...
11                             Buffers: shared hit=94
12                                          Planning:
13                             Buffers: shared hit=11
14                            Planning Time: 0.215 ms
15                          Execution Time: 29.347 ms

### Reflection

**!!! NOTE: Цифри (вимірювані метрики) після повторного запуску змінюються.**

1. **Порівняння до і після GIN індексу**. Після створення GIN-індексу idx_t7_events_payload_gin_pathops план виконання змінився з Seq Scan на комбінацію Bitmap Index Scan і Bitmap Heap Scan. Для запиту з умовою payment_method = card фактичний час виконання зменшився з 70.927 мс до 9.589 мс, тобто приблизно у 7.4 раза. Загальний cost також знизився. Другий запит із пошуком referrer = google виконався за 10.896 мс і теж використав GIN-індекс. Отже, GIN-індекс суттєво покращив виконання запитів із пошуком за вмістом JSONB, хоча кількість використаних блоків таблиці залишилася практично незмінною.

| Показник | До GIN-індексу | Після GIN (приклад 1) | Після GIN (приклад 2) |
|---|---:|---:|---:|
| Умова пошуку | `payment_method = card` | `payment_method = card` | `referrer = google` |
| Основний оператор | Seq Scan | Bitmap Heap Scan | Bitmap Heap Scan |
| Індексний оператор | Відсутній | Bitmap Index Scan | Bitmap Index Scan |
| Загальний cost | 1757.40 | 1106.53 | 1079.86 |
| Execution Time (ms) | 70.927 | 9.589 | 10.896 |
| Кількість знайдених рядків | 3334 | 3334 | 2500 |
| Рядків відкинуто фільтром | 46666 | - | - |
| Buffers: shared hit | 1000 | 1004 | 1004 |
| Planning Time (ms) | 0.187 | 0.405 | 0.216 |
| Використання GIN-індексу | Ні | Так | Так |
| Прискорення | - | У 7.4 раза | Немає даних для порівняння |


2. **Чому GIN допомагає для @> containment, але не є найкращим рішенням для payload ->> 'device' = 'mobile'?** GIN працює з операторами @>, ?, @?, а payload ->> 'device' = 'mobile' - це звичайна рівність над text. Тому навіть за наявності GIN план лишився Seq Scan. Тому тут підходить Expression індекс який дозволив знизити час виконання запиту із 35.032 мс до 5.085 мс.

3. **Який read/write trade-off створює GIN-індекс: що пришвидшується, а що може стати дорожчим?** GIN-індекс доцільний, коли переважають запити на пошук і фільтрацію JSONB. Якщо таблиця часто оновлюється, додаткові витрати на підтримку індексу можуть зменшити загальну продуктивність запису. Тому вибір індексу залежить від співвідношення операцій читання та запису.

4. **Коли у ML data infrastructure ви обрали б JSONB, а коли - нормалізовану таблицю?** JSONB забезпечує гнучкість, а нормалізація - передбачувану структуру, цілісність і зручність аналітики. У реальній ML-інфраструктурі їх доцільно комбінувати: зберігати оригінальні дані гнучко, а ознаки, критичні для навчання та прогнозування, оформлювати у структурованому вигляді.
* JSONB - для сирих подій, нестабільних метаданих і додаткових атрибутів.
* Нормалізовані таблиці - для основних сутностей, стабільних ознак і зв'язків.
* ML feature store або аналітичне сховище - для підготовлених ознак, версіонування та формування навчальних датасетів.

5. **Як би ви додали новий event-type refund у JSONB-підході та в normalized-підході? Які міграційні дії потрібні?** Обидва підходи різняться тим, де опиняється перевірка даних. У JSONB схему не треба міняти, але валідацію доводиться додавати окремо. У normalized-підході потрібна міграція, зате всі правила закладено в самій схемі. У JSONB-підході refund додається одним INSERT з новим event_type, без DDL. Валідацію треба додати окремо: CHECK ... NOT VALID по event_type = 'refund' або перевірку в ETL. Ще треба переглянути запити без фільтра за event_type. У normalized-підході потрібна міграція: UNIQUE на t7_hw_checkouts_norm.order_id, нова таблиця t7_hw_refunds_norm з FOREIGN KEY, CHECK (amount > 0) та індексом на order_id, backfill наявних подій і зміна ETL.